eureka:
  client:
    serviceUrl: #\u6ce8\u518c\u4e2d\u5fc3\u7684\u6ce8\u518c\u5730\u5740
      defaultZone: http://127.0.0.1:8081/eureka/
server:
  port: 8083  #\u670d\u52a1\u7aef\u53e3\u53f7
spring:
  application:
    name: consumer