#指定日志输出文件
logging:
  file: "logs/sso-config.log"
info:
  name : "配置中心"

server:
  port: 8888
  context-path: /config
spring:
  #profiles:
  ##native 默认访问 本地的resources/config下的文件
  #  active: native

  application:
    name: config
  cloud:
    config:
      server:
        native:
#          searchLocations: classpath:/config
        git:
          uri: https://github.com/zhenzhanlong/config-repo.git
          search-paths: config-repo
          username: zhanlong1988@126.com
          password: github147
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/
  refresh:
      sensitive: false
